### ISSUE TITLE
wpa_supplicant.conf will not open

### ISSUE THREAD

**Issue by ChristianLundmand** [OpenScan-org/OpenScan2#80]
After flashing a new image (the pre-compiled image from OpenScan) to my SD card I cannot access the wpa_supplicant.conf file. Windows says the file is damaged. I tried reflashing the image to no avail. I tried renaming the file .txt (just to try something) but I cannot be renamed as it is damaged. How should I proceed?

**Comment by tdub415** [comment]
the wpa_supplicant file was broken for me in the boot directory.  I'd suggest connecting via ethernet and SSHing into your pi.

I found the the network interfaces had wifi to have wifi be a manual IP assignment rather than DHCP.

to fix it, i did the following:

sudo nano /etc/network/interfaces


changed the line reading "iface wlan0 inet manual" to be "iface wlan0 inet dhcp"

as well as the other chagnes listed here:

https://weworkweplay.com/play/automatically-connect-a-raspberry-pi-to-a-wifi-network/


I now have access to my scanner via wifi, hope it helps.

**Comment by josepmy** [comment]
@ChristianLundmand me too and I fix in the same way as explained @tdub415
